const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const S={user:null,items:[],offers:{incoming:[],outgoing:[]},view:'market',auth:'login',cat:'全部',q:'',modal:null,mode:'item',preview:null};
const e=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const yuan=n=>`¥${Number(n||0).toLocaleString('zh-CN')}`, mine=i=>i.ownerId===S.user?.id, get=id=>S.items.find(i=>i.id===id), initials=n=>(n||'?').trim()[0].toUpperCase();
async function api(url,opt={}){let r=await fetch(url,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'操作未完成，请稍后重试。');return j}
function toast(msg,kind=''){let x=document.createElement('div');x.className=`toast ${kind}`;x.textContent=msg;$('#toast-region').append(x);setTimeout(()=>x.remove(),3500)}
async function init(){S.user=(await api('/api/session')).user;if(S.user){let[a,b]=await Promise.all([api('/api/items'),api('/api/offers')]);S.items=a.items;S.offers=b}render()}
const tile=()=>'<span class="rainbow-tile"><i></i><i></i><i></i><i></i><i></i></span>';
const btn=(txt,action,data='',klass='primary')=>`<button class="button ${klass}" data-action="${action}" ${data}>${e(txt)}${klass==='primary'||klass==='pink'?tile():''}</button>`;
const avatar=u=>`<span class="avatar">${e(initials(u?.name))}</span>`;
const pic=(i,c='photo')=>`<div class="${c} ${e(i.color||'')}">${i.imageUrl?`<img src="${i.imageUrl}" alt="${e(i.title)}">`:`<b>${e(i.emoji||'📦')}</b>`}</div>`;
function auth(){let reg=S.auth==='register';return `<main class="auth"><section class="auth-sky"><div class="brand"><b>↔</b>换物记</div><div><p class="kicker">LOCAL EXCHANGE MARKET</p><h1>把喜欢的<br><em>交换</em>回来。</h1><p>发布你的闲置，遇见另一个人的刚刚好。</p></div><img src="/assets/rainbow-exchange-hero.png" alt="彩虹礼物盒"></section><section class="auth-panel"><div class="brand mobile"><b>↔</b>换物记</div><form id="auth-form" class="pillow auth-box"><p class="kicker">WELCOME TO SWAPBOOK</p><h2>${reg?'加入交换俱乐部':'欢迎回来'}</h2><p class="muted">${reg?'创建账户，开始让好物继续流转。':'登录后继续你的交换旅程。'}</p><div class="tabs"><button type="button" class="${!reg?'active':''}" data-action="auth" data-mode="login">登录</button><button type="button" class="${reg?'active':''}" data-action="auth" data-mode="register">注册</button></div>${reg?'<label>昵称<input required name="name" minlength="2" maxlength="24" placeholder="例如：小林"></label>':''}<label>邮箱<input required type="email" name="email" placeholder="you@example.com"></label><label>密码<input required type="password" name="password" minlength="6" placeholder="至少 6 位"></label>${btn(reg?'创建账户':'登录','submit','','primary')}<p class="demo">演示物主：<b>mia@swap.local / mia123</b><br>或 <b>ken@swap.local / ken123</b></p></form></section></main>`}
function nav(){let n=S.offers.incoming.filter(x=>x.status==='pending').length;return `<header><div class="brand"><b>↔</b>换物记</div><nav>${[['market','逛市场'],['mine','我的物品'],['trades',`交易请求${n?` <i>${n}</i>`:''}`]].map(([v,l])=>`<button class="${S.view===v?'active':''}" data-action="view" data-view="${v}">${l}</button>`).join('')}</nav><div class="account">${avatar(S.user)}<span>${e(S.user.name)}</span><button data-action="logout">退出</button></div></header>`}
function product(i){let owner=i.owner||{};return `<article class="product">${pic(i)}<div><div class="meta"><span>${e(i.category)}</span><span>${e(i.condition)}</span></div><h3>${e(i.title)}</h3><p>${e(i.description)}</p><div class="product-foot"><span>${avatar(owner)}${e(owner.name)}</span><b>${yuan(i.price)}</b></div>${mine(i)?'<button class="button neutral" disabled>这是你的物品</button>':btn('交换它','offer',`data-id="${i.id}"`)}</div></article>`}
function market(){let cats=['全部',...new Set(S.items.map(x=>x.category))],q=S.q.toLowerCase(),arr=S.items.filter(x=>(S.cat==='全部'||x.category===S.cat)&&(!q||`${x.title} ${x.description} ${x.category}`.toLowerCase().includes(q)));return `<main><section class="hero"><div><p class="kicker">LOCAL EXCHANGE MARKET · 01</p><h1>好东西<br>不该被忘记。</h1><p>用一件你愿意分享的物品，换一件真正需要的。也可以用现金报价，礼貌地问一问。</p><div class="hero-buttons">${btn('发布我的物品','view','data-view="mine"')} ${btn('开始挑选','jump','','pink')}</div></div><aside><span>✦</span><span>✦</span><img src="/assets/rainbow-exchange-hero.png" alt="彩虹礼物盒"><div><b>${S.items.length} 件好物</b><small>正在等待新主人</small></div></aside></section><section class="listing" id="listing"><div class="section-head"><div><p class="kicker">PICK A TREASURE</p><h2>市场里的新发现</h2></div><label class="search">⌕<input id="search" value="${e(S.q)}" placeholder="搜索物品或类别"></label></div><div class="filters">${cats.map(x=>`<button class="${S.cat===x?'active':''}" data-action="cat" data-cat="${e(x)}">${e(x)}</button>`).join('')}</div><div class="grid">${arr.map(product).join('')||'<p class="empty">没有找到匹配的好物，换一个关键词试试。</p>'}</div></section></main>`}
function minePage(){let arr=S.items.filter(mine);return `<main class="page"><div class="title"><p class="kicker">MY LITTLE SHOP</p><h1>我的交换清单</h1><p>让别人清楚地知道你的物品是什么样子，也让它更容易遇到新主人。</p></div><div class="cols"><section class="pillow form"><h2>发布一件物品</h2><form id="item-form"><label>物品名称<input required name="title" maxlength="48" placeholder="例如：手冲咖啡壶"></label><div class="two"><label>类别<select name="category"><option>家居</option><option>数码</option><option>书籍</option><option>服饰</option><option>植物</option><option>其他</option></select></label><label>成色<input required name="condition" maxlength="32" placeholder="例如：九成新"></label></div><label>描述<textarea required name="description" maxlength="240" placeholder="品牌、尺寸、使用情况…"></textarea></label><label>现金参考价（元）<input required name="price" type="number" min="1" placeholder="例如：120"></label><label class="upload"><input id="image" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><span>${S.preview?`<img src="${S.preview}" alt="图片预览">`:'＋'}</span><em>${S.preview?'点击可替换图片':'添加实拍图（可选，3MB 内）'}</em></label>${btn('发布到市场','submit')}</form></section><section class="pillow my-items"><div class="row"><h2>正在上架</h2><b>${arr.length} 件</b></div>${arr.length?arr.map(i=>`<article class="mini">${pic(i,'mini-pic')}<div><b>${e(i.title)}</b><p>${e(i.category)} · ${e(i.condition)} · ${yuan(i.price)}</p></div><button data-action="delete" data-id="${i.id}">×</button></article>`).join(''):'<p class="empty">你还没有上架物品。发布第一件，交换就可以开始了。</p>'}</section></div></main>`}
function offerCard(o,incoming){let it=o.targetItem||{},line=o.type==='cash'?`现金报价 ${yuan(o.cashAmount)}`:`用「${o.offeredItem?.title||'一件物品'}」交换`;return `<article class="deal"><div><span class="status ${o.status}">${({pending:'等待回应',accepted:'已同意',declined:'未同意'})[o.status]}</span><time>${new Date(o.createdAt).toLocaleDateString('zh-CN')}</time></div><h3>${incoming?`${e(o.proposer?.name||'用户')} 想交换「${e(it.title)}」`:`你想交换「${e(it.title)}」`}</h3><p>${incoming?line:(o.type==='cash'?`你的报价为 ${yuan(o.cashAmount)}`:`你用「${e(o.offeredItem?.title||'一件物品')}」提出交换`)}</p>${o.status==='accepted'?'<small>已达成一致，请自行安排交接。</small>':''}${incoming&&o.status==='pending'?`<footer>${btn('同意','decision',`data-id="${o.id}" data-status="accepted"`)}<button class="button soft" data-action="decision" data-id="${o.id}" data-status="declined">婉拒</button></footer>`:''}</article>`}
function trades(){return `<main class="page"><div class="title"><p class="kicker">EXCHANGE DESK</p><h1>交易请求</h1><p>物主可在这里同意或婉拒请求；达成一致后，双方自行安排交接和付款。</p></div><div class="cols"><section class="pillow"><div class="row"><h2>收到的请求</h2><b class="orb">${S.offers.incoming.filter(x=>x.status==='pending').length}</b></div>${S.offers.incoming.map(x=>offerCard(x,true)).join('')||'<p class="empty">暂时还没有人对你的物品发出请求。</p>'}</section><section class="pillow"><div class="row"><h2>我发出的请求</h2><b class="orb pink-orb">${S.offers.outgoing.length}</b></div>${S.offers.outgoing.map(x=>offerCard(x,false)).join('')||'<p class="empty">去市场挑一件喜欢的物品，发出请求吧。</p>'}</section></div></main>`}
function modal(){let it=get(S.modal),choices=S.items.filter(mine);return `<div class="shade" data-action="close"><section class="modal"><button class="x" data-action="close">×</button><p class="kicker">MAKE AN OFFER</p><h2>把喜欢的带回家</h2><div class="wanted">${pic(it,'wanted-pic')}<span><b>${e(it.title)}</b><small>物主：${e(it.owner?.name)} · 参考 ${yuan(it.price)}</small></span></div><div class="switch"><button class="${S.mode==='item'?'active':''}" data-action="mode" data-mode="item">拿物品交换</button><button class="${S.mode==='cash'?'active':''}" data-action="mode" data-mode="cash">给现金报价</button></div><form id="offer-form">${S.mode==='item'?(choices.length?`<div class="choices">${choices.map((x,n)=>`<label><input type="radio" name="offeredItemId" value="${x.id}" ${!n?'checked':''}>${pic(x,'choice-pic')}<span><b>${e(x.title)}</b><small>${e(x.condition)} · ${yuan(x.price)}</small></span></label>`).join('')}</div>`:'<p class="empty">先去「我的物品」发布一件可交换的物品吧。</p>'):`<label class="cash">你的报价 <span>¥ <input name="cashAmount" required type="number" min="1" value="${it.price}"></span></label>`}<p class="modal-note">提交后，物主会在交易请求中看到你的提议。</p><footer><button type="button" class="button soft" data-action="close">取消</button>${btn('发送请求','submit','type="submit"',choices.length||S.mode==='cash'?'primary':'neutral')}</footer></form></section></div>`}
function render(){app.innerHTML=S.user?`<div class="site">${nav()}${S.view==='mine'?minePage():S.view==='trades'?trades():market()}</div>${S.modal?modal():''}`:auth();bind()}
function bind(){$$('[data-action]').forEach(x=>x.addEventListener('click',act));$('#auth-form')?.addEventListener('submit',login);$('#item-form')?.addEventListener('submit',add);$('#offer-form')?.addEventListener('submit',sendOffer);$('#image')?.addEventListener('change',image);$('#search')?.addEventListener('input',ev=>{S.q=ev.target.value;render();$('#search').focus()})}
async function act(ev){let x=ev.currentTarget,a=x.dataset.action;if(a==='auth'){S.auth=x.dataset.mode;return render()}if(a==='view'){S.view=x.dataset.view;return render()}if(a==='cat'){S.cat=x.dataset.cat;return render()}if(a==='jump')return $('#listing')?.scrollIntoView({behavior:'smooth'});if(a==='offer'){S.modal=x.dataset.id;S.mode='item';return render()}if(a==='close'&&(x.tagName==='BUTTON'||ev.target===x)){S.modal=null;return render()}if(a==='mode'){S.mode=x.dataset.mode;return render()}try{if(a==='logout'){await api('/api/auth/logout',{method:'POST',body:'{}'});S.user=null;S.items=[];S.offers={incoming:[],outgoing:{}};render();return toast('已安全退出。')}if(a==='delete'){await api('/api/items/'+x.dataset.id,{method:'DELETE'});await refresh();render();toast('物品已下架。')}if(a==='decision'){await api('/api/offers/'+x.dataset.id,{method:'PATCH',body:JSON.stringify({status:x.dataset.status})});await refresh();render();toast(x.dataset.status==='accepted'?'已同意这次交换。':'已婉拒这次交换。')}}catch(err){toast(err.message,'error')}}
async function refresh(){let[a,b]=await Promise.all([api('/api/items'),api('/api/offers')]);S.items=a.items;S.offers=b}
async function login(ev){ev.preventDefault();try{let url=S.auth==='register'?'/api/auth/register':'/api/auth/login';S.user=(await api(url,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(ev.currentTarget)))})).user;await refresh();render();toast('欢迎来到换物记！')}catch(err){toast(err.message,'error')}}
const data=f=>new Promise((ok,no)=>{let r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});
async function image(ev){let f=ev.target.files[0];if(!f)return;if(f.size>3*1024*1024)return toast('图片需小于 3MB。','error');S.preview=await data(f);render()}
async function add(ev){ev.preventDefault();try{let d=Object.fromEntries(new FormData(ev.currentTarget));if(S.preview)d.imageUrl=(await api('/api/uploads',{method:'POST',body:JSON.stringify({imageData:S.preview})})).imageUrl;await api('/api/items',{method:'POST',body:JSON.stringify(d)});S.preview=null;await refresh();render();toast('物品已发布到市场。')}catch(err){toast(err.message,'error')}}
async function sendOffer(ev){ev.preventDefault();try{let d=Object.fromEntries(new FormData(ev.currentTarget));await api('/api/offers',{method:'POST',body:JSON.stringify({targetItemId:S.modal,type:S.mode,...d})});S.modal=null;await refresh();S.view='trades';render();toast('请求已发送，等待物主回应。')}catch(err){toast(err.message,'error')}}
init();
